language: node_js
os: linux
dist: xenial
node_js:
  - "14"
cache:
  npm: true
  directories:
    - node_modules
install:
  - npm install
before_deploy:
  - npm install -g travis-ci-cloudfront-invalidation gatsby
  - npm run buildTravis
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  skip_cleanup: true
  local_dir: ./public
  on:
    branch: master
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $CLOUDFRONT_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
